name: mario_party_rl
services:
  virutal_frame_buffer_server:
    build:
      context: ./virutal_frame_buffer_server
      dockerfile: ./Dockerfile
    environment:
      - PULSE_SERVER=mupen64plus_emulator
    ports:
      - "6000:6000"
    entrypoint:  ['/scripts/start_xvfb.sh']
  vnc_server:
    build:
      context: ./vnc_server
      dockerfile: ./Dockerfile
    environment:
      - DISPLAY=virutal_frame_buffer_server:0
    ports:
      - "5900:5900"
    entrypoint: ['/scripts/start_vnc_server.sh']
    depends_on: [ virutal_frame_buffer_server ]
  mupen64plus_emulator:
    build:
      context: ./mupen64plus
      dockerfile: ./Dockerfile
      args:
        MARIO_PARTY_RL_USER: ${MARIO_PARTY_USER-mario}
        UID: ${UID-1000}
        GID: ${GID-1000}
    user: ${UID-1000}:${GID-1000}
    environment:
      - DISPLAY=virutal_frame_buffer_server:0
    ports:
      - "4713:4713"
    command: ['/scripts/start_mupen64plus.sh']
    depends_on: [virutal_frame_buffer_server, vnc_server]